// Code generated by "stringer -type=CardValue,CardSuit -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
}

const _CardValue_name = "Ace2345678910JackQueenKing"

var _CardValue_index = [...]uint8{0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 22, 26}

func (i CardValue) String() string {
	i -= 1
	if i < 0 || i >= CardValue(len(_CardValue_index)-1) {
		return "CardValue(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CardValue_name[_CardValue_index[i]:_CardValue_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-0]
	_ = x[Diamonds-1]
	_ = x[Clubs-2]
	_ = x[Hearts-3]
}

const _CardSuit_name = "SpadesDiamondsClubsHearts"

var _CardSuit_index = [...]uint8{0, 6, 14, 19, 25}

func (i CardSuit) String() string {
	if i < 0 || i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
